Created auth Vuex store module
neit-kite/kite pull request #32
Opened 2019-02-08 16:08 UTC by RetWolf

- Stores basic user information in Vuex for easy access
- Setup data to persist over page refresh using session storage
- Converted client-side route authentication to use Vuex for faster load times

2019-02-09 18:57 UTC, KyloRilo approved these changes

2019-02-11 23:23 UTC, ArowShot approved these changes

2019-02-11 23:56 UTC, ianfabs approved these changes

2019-02-11 23:59 UTC, ianfabs requested changes
Fix that `component: this` thing

2019-02-12 18:14 UTC, ianfabs approved these changes

2019-02-12 18:27 UTC, merged