Container apollo
neit-kite/kite pull request #43
Opened 2019-02-25 20:23 UTC by ianfabs

Added apollo into the containers components, as well as the containers page.

2019-02-26 17:26 UTC, KyloRilo approved these changes

2019-02-26 17:52 UTC, ArowShot approved these changes

2019-02-26 23:15 UTC, mattsre requested changes
See reasoning in #44

2019-02-28 19:00 UTC, RetWolf commented
I made a commit to #44 which fixes my issues with the pull request. Because that PR includes all the changes in this one, I do not plan on fixing this branch as well. I feel we should simply merge #44 and close this PR because all the functionality introduced here is also in #44.

2019-03-01 23:45 UTC, closed without merging