Container delete
neit-kite/kite pull request #44
Opened 2019-02-25 21:34 UTC by ianfabs

Marked containers as deleted instead of actually deleting them

2019-02-26 17:25 UTC, KyloRilo approved these changes

2019-02-26 17:52 UTC, ArowShot approved these changes

2019-02-26 18:51 UTC, mattsre requested changes
There are some things in both this pull request and the container apollo pull request that I don't agree with, and don't approve of. These include:

- The client side router pulling new information on each pull. This currently does nothing because the API endpoint it calls interfaces with the cache rather than the database. I will update this myself.
- The updated Nginx config doesn't work properly with the build.

2019-02-26 18:51 UTC, mattsre commented on kite-api/src/resolvers/container.resolver.js
> +      return ((deleted != null) ? c.filter(cn => cn.deleted === deleted) : c);
I think that this can be written better. Readability is pretty poor, and at a first glance this looks like gibberish. Personally I think data manipulation should be done on the client side, but that is up for discussion.

2019-02-26 18:51 UTC, mattsre commented on kite-api/src/utils/container.util.js
> +  /* If it follows the guidelines, then check for illegal characters */
Please update this comment to reflect the actual functionality of the check below

2019-02-26 18:51 UTC, mattsre commented on kite-api/src/utils/container.util.js
> +  }else throw new Error("Docker: Container name must match ^([aA-zZ0-9-_]+)$");
The user will not understand what this Regex is. Please update this error message to something that a user will understand.

2019-02-28 18:57 UTC, mattsre approved these changes

2019-02-28 18:58 UTC, RetWolf commented
Assuming all checks pass, this can finally be merged. I have made the changes removing the code that I will be rewriting and I fixed the Nginx config.

2019-03-02 00:13 UTC, closed without merging